name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - run: GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o main ./main.go
      - uses: actions/upload-artifact@v2
        with:
          name: main
          path: main
